mesosphere/spark-build

package/package.json

https://mesosphere.atlassian.net/browse/DOCS-1034

fixed docs links in package.json

---

docs/user-docs.md

@sascala Here is my initial draft.

Rough draft documenting Python support and Spark shell.

---

docs/user-docs.md

--py-files documentation

---

bin/jenkins.sh

Additional flags in Spark distribution build.

Added Hive support, as well as SparkR

---

docker/Dockerfile
tests/jobs/dataframe.R
tests/test.py

1. Added R to Docker image.
2. Added SparkR test, disabled for now. Test runs the "dataframe.R" example script from Spark examples.
@mgummelt

Add R to docker image and tests

---

bin/jenkins-dist-publish.sh
bin/jenkins.sh

fix mesos profile in build

---

docs/run-job.md

[SPARK-382] Document versions

---

tests/test.py

[SPARK-380] kerberos integration test

---

docs/history-server.md

relates to: https://mesosphere.atlassian.net/browse/DOCS-1607

code snippet fix

---

docker/Dockerfile

Switched to latest JRE, to be consistent with other Infinity services.
cc @mgummelt for review

Updated JRE

---

docs/limitations.md
docs/quick-start.md
docs/run-job.md
docs/spark-shell.md

Added documentation for SparkR

---

tests/test.py

(1) Uninstall and janitor in module teardown, because there are other framework tests running after Spark tests on the same cluster.
(2) Some changes related to new HDFS: new endpoint, number of tasks, longer timeout.

Fixed Spark test to run within Framework Tests

---

docker/Dockerfile

The JRE URL at downloads.mesosphere.com now has a redirect. I added a "-L" flag for curl to follow the redirect.

Added a redirect flag to the curl command in Dockerfile

---

tests/test_soak.py

Fixed the calls to utils.run_tests() in soak test.
Tested in my own CCM cluster.

Fixed terasort soak test after refactor

---

cli/dcos-spark/submit_builder.go

Add `--isR` and `--isPython` boolean flags to the command line to (optionally) override internal parsing of the application URL.

[SPARK-512] expose isR and isPython spark run args

---

docs/hdfs.md

Spark checkpoint docs

---

docker/runit/service/spark/run

By default enable the sandbox uri. Check at the bottom of the image the uri.

Adds sandbox uri

---

Makefile
tools/build_cli.sh
tools/build_framework.sh
tools/build_publishable.sh
tools/release.sh
tools/release_artifacts.sh
tools/setup_permissions.sh

- Makes some make variables configurable form the env. This is more close to bash practices which is very convenient.
- Use #!/usr/bin/env bash for consistency. Some files used it already like tools/init_paths.sh

Some improvements for the build process

---

docs/hdfs.md
tests/test_spark.py

Use environment based secrets for the S3 test job.

[SPARK-609] use environment based secrets for S3Job

---

Makefile

@susanxhuynh I know the purpose was to hardcode some values and release. I also need this for the CI stuff I am doing. I think it does not change anything for your side :)

Make properties configurable

---

scale-tests/deploy-dispatchers.py
tests/requirements.txt

https://jira.mesosphere.com/browse/SPARK-724

[SPARK-724] Allow config of JSON service options via CLI

---

docker/Dockerfile
tools/universe/package_builder.py

Closed the previous PR. Addresses, https://jira.mesosphere.com/browse/DCOS-43949

[DCOS-43949] Update JRE to server-jre-8u192

---

docs/install.md
docs/job-scheduling.md
docs/quickstart.md
docs/usage-examples.md
history/universe/package.json
manifest.json
spark-testing/spark_utils.py
universe/package.json

Resolves [DCOS-49231](https://jira.mesosphere.com/browse/DCOS-49231)
Update Spark distribution version to the current release
* integration tests from current repo
* soak testing on DC/OS 1.10, 1.11, 1.11s, 1.12s, 1.13s
N/A

[DCOS-49231] Spark 2.4.0 release version update

---

manifest.json
spark-testing/dcos_utils.py
spark-testing/docker_utils.py
spark-testing/spark_utils.py
tests/test_mesos_checkpointing.py

Resolves [DCOS-40974](https://jira.mesosphere.com/browse/DCOS-40974)
Changes:
* new integration tests for Mesos Checkpointing support for Spark Drivers
* minor refactorings to reuse existing functionality
Integration tests from [mesosphere/spark-build](https://github.com/mesosphere/spark-build)
N/A

[DCOS-40974] Mesos checkpointing support for Spark Drivers

---

scale-tests/deploy-dispatchers.py
testing/sdk_cmd.py
testing/sdk_marathon.py

Workaround for [DCOS-51007](https://jira.mesosphere.com/browse/DCOS-51007)
Also checks the rc rather then stderr for exiting.
We ran MWT14 with these changes

fixes introduced in MWT14

---

spark-testing/dcos_utils.py
testing/sdk_security.py
tests/jobs/scala/README.md
tests/jobs/scala/build.sbt
tests/jobs/scala/src/main/scala/SecretConfs.scala
tests/test_spark_secrets.py

Resolves [DCOS-41593](https://jira.mesosphere.com/browse/DCOS-41593)
* Adds multiple integration tests for various configurations of Mesos Secrets support.
It is tested manually submitting jobs.
Adds Integration Tests for Mesos Secrets

[DCOS-41593][Integration Tests] Add Mesos Secrets support to the spark dispatcher

---

docker/Dockerfile
docker/runit/init.sh
docker/spark_health.sh
tests/test_tls.py
universe/config.json
universe/marathon.json.mustache

Resolves [DCOS-52206](https://jira.mesosphere.com/browse/DCOS-52206).
* Changes config.json to provide option for TLS
* Changes marathon with relevant environment variables 
* Test manually
* Adds feature of TLS

[DCOS-52206] Add TLS support for Spark REST submission server and client

---

README.md

Resolves [ticket ID](url)
(Please fill in changes proposed in this fix)
(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)
(If tests are complex, please provide steps to test locally)
(Please include a short summary for release notes if applicable)

Add build info in README.md
