bin/test.sh

In Jenkins logs:
```
bin/test.sh: line 13: [: missing `]'
```

Fix bash syntax error

---

conf/spark-env.sh

@mgummelt This fixes the problem where SPARK_LOCAL_IP is not set properly because it gets overwritten by an empty LIBPROCESS_IP.

Make sure LIBPROCESS_IP is defined before setting SPARK_LOCAL_IP to it.

---

docs/user-docs.md

Versions:
DCOS: 1.7
Spark: 1.0.4-2.0.1
HDFS: 0.9.1-2.6.0
When trying to get the history server working with DCOS's version of HDFS and SPARK, it did configure itself to the DCOS HDFS by default. This is purely a documentation fix to show that the HDFS actually serves the configuration xmls from `/v1/connection`, not `v1/connect`  Using this value in the `hdfs.config-url` made the history server work as expected.

DCOS HDFS uses /v1/connection 

---

cli/dcos_spark/cli.py

If you try to run dcos spark log after the task has finished it would error out since it cannot find the task. The error would look something like :
```
Traceback (most recent call last):
File "/Users/harpreet/.dcos/subcommands/spark/env/bin/dcos-spark", line 11, in <module>
sys.exit(main())
File "/Users/harpreet/.dcos/subcommands/spark/env/lib/python2.7/site-packages/dcos_spark/cli.py", line 110, in main
return log_job(args)
File "/Users/harpreet/.dcos/subcommands/spark/env/lib/python2.7/site-packages/dcos_spark/cli.py", line 67, in log_job
task = mesos.get_master(dcos_client).task(args['<submissionId>'])
File "/Users/harpreet/.dcos/subcommands/spark/env/lib/python2.7/site-packages/dcos/mesos.py", line 380, in task
'Cannot find a task with ID containing "{}"'.format(fltr)) …
```

Show spark log even after the task has completed

---

docs/limitations.md

Added documentation about not supporting Spark app development and Spark shell needing to run inside cluster.

Added limitations to docs: app development and Spark shell

---

bin/dist.sh
bin/jenkins-dist-publish.sh
bin/jenkins-dist-test.sh
bin/jenkins-package-publish.sh
bin/jenkins.sh
bin/make-docker.sh
bin/universe.sh
docs/install.md
docs/spark-versions.md
manifest.json
package/config.json

This makes it so the spark-release job will publish a version of Spark for each hadoop profile (2.4, 2.6, 2.7).
It also makes it so the spark-build-release job will publish a docker image for each hadoop profile.  We still only publish one DC/OS package per release, but the user can customize the DC/OS package with a different docker image via `service.docker-image`.

Multiple hadoop profiles

---

bin/make-docker.sh
bin/test.sh
conf/spark-env.sh
tests/test.py

cc @susanxhuynh for review
1) Updates spark-env.sh to use DNS only when it's available (because CNI requires it)
2) Adds a CNI integration test
3) Refactors the tests to use py.test rather than python directly (same as other infinity frameworks)

[SPARK-332] Adds CNI support

---

bin/test.sh

In strict mode, call setup_permissions.sh for hdfs.

Setup permissions for hdfs role

---

bin/test.sh
tests/test.py

- Temporarily using a stub-universe for HDFS until strict mode support is released, just to get Framework Test to pass. Should be reverted when a new version of HDFS is released.
- Specify the principal and secret when install HDFS in strict mode.
- Specify security configs for Spark driver in strict mode.

Fix the shakedown tests for strict mode

---

tests/test_soak.py

Metronome throws an exception if you try to add an existing job.
To avoid this, I added a check of whether the hdfs_delete_terasort_files job exists before adding it.

Check if the hdfs_delete_terasort_files job exists before adding it

---

tests/jobs/python/long_running.py
tests/test_recovery.py
tests/test_spark.py
tests/utils.py

Make driver failover_timeout configurable to allow for temporary disconnection between driver and Mesos master.
- The upstream PR is here: https://github.com/apache/spark/pull/18674
- In spark-build, I added an integration test (currently disabled) that disconnects the driver from the master.
- This PR does not include the extra teardown that is needed in some cases.

[SPARK-478] Make driver failover_timeout configurable

---

conf/spark-env.sh
dispatcher/cli/Makefile
dispatcher/cli/dcos_spark/cli.py
dispatcher/cli/dcos_spark/spark_submit.py
docker/Dockerfile
docker/runit/init.sh
docs/hdfs.md

Add `--kerberos-principal` and `--keytab-secret-path` to the CLI, the former must match the key table in the secret indicated by the latter. Tested manually against a kerberized HDFS cluster. 
Todo:
~test against 1.9 file-based secrets~

[Spark-483] Add Kerberos principal and secret-based key tab to the CLI, also update libmesos in Dockerfile

---

universe/marathon.json.mustache

The property service.docker-image in config.json is not used. This is a nice property which helps people use a spark image other than the one provided already by Mesosphere.
Tested by deriving an image:
FROM mesosphere/spark:1.1.0-2.1.1-hadoop-2.6
ADD mesos-cluster-dispatcher.properties /opt/spark/dist/conf/mesos-cluster-dispatcher.properties
WORKDIR /opt/spark/dist

Fix Spark Dispatcher's image config

---

tests/utils.py

There's a newly introduced bug in the latest version of hdfs in the Universe (2.0.2-xyz), in one of the s3n config values. This prevents Spark from reading from S3 when it is configured to run with HDFS. To get the CI tests passing again, I have temporarily pinned the version of HDFS to the previous version (2.0.1-xyz).
Can unpin when the hdfs config bug is fixed.

Temporarily pinned the hdfs version to get 'test_s3' CI test passing

---

cli/bin/build-go.sh
cli/dcos-spark/cli_test.go
cli/dcos-spark/submit_builder.go

Spaces between arguments break the spark cli:
https://github.com/mesosphere/spark-build/blob/master/cli/dcos-spark/submit_builder.go#L302
This will fail when the job is run:
```
dcos spark run --verbose --submit-args="--conf spark.streaming.fileStream.minRememberDuration=1200s__--driver-cores 1 --conf spark.cores.max=4 --driver-memory 1024M --class com.lightbend.fdp.spark.test.FileStreamWithCheckpointing https://s3-eu-west-1.amazonaws.com/fdp-stavros-test/checkpointing-test-assembly-1.0-SNAPSHOT.jar --checkpointDirectory /checkpoint --outputDirectory /output --inputDirectory /watched"dcos spark run --verbose --submit-args="--conf spark.streaming.fileStream.minRememberDuration=1200s --driver-cores 1 --conf spark.cores.max=4 --driver-memory 1024M --class …
```

Spark dcos CLI breaks with multiple spaces

---

cli/dcos-spark/submit_builder.go
manifest.json
tests/resources/secrets-opts.txt

Published distribution from [tag](https://github.com/mesosphere/spark/tree/custom-2.2.0-2) and updated manifest. Also fixed CLI `spark.mesos.driver.secret.name` -> `spark.mesos.driver.secret.names` (required in new version).

Update the spark distribution to 2.2.0-2 and update the key tab props to plural 

---

conf/spark-env.sh

Older versions of the Spark package used `SPARK_MESOS_KRB5_CONF_BASE64` to represent the krb5.conf, this allows someone to re-use their older dispatcher with the newer packages.

[SPARK-562] Add old envvar option

---

universe/config.json
universe/marathon.json.mustache

Use the Mesos Universal Container Runtime (UCR) for the dispatcher. This allows `dcos task exec`. The health check and Spark signal handler also work better now.

[SPARK-585] Configurable deployment of Dispatcher on UCR

---

docs/release-notes.md

https://jira.mesosphere.com/browse/COPS-1865
I'm not sure I put this in the right right release.

-Dspark args no longer supported

---

tests/test_kafka.py
tests/test_spark.py

Added "smoke" mark for smoke tests, to be run against development versions of DC/OS. Includes all tests except HDFS ones, as HDFS take about 15 minutes to install/uninstall. The smoke test job, including cluster setup, should complete within an hour.

[INFINITY-1212] Added "smoke" mark for smoke tests

---

docs/limits.md

Addresses: [SPARK-691](https://jira.mesosphere.com/browse/SPARK-691)
This PR updates DC/OS Spark docs to report how much scale-testing we've done.
DC/OS Spark has been run on a 2.5K core cluster. 
The plan was to test on 10K cores but that was cost prohibitive.

Add limits page for Spark (#286)

---

monitoring/dashboards/SparkJobsSummary.json

Since Kafka jobs now have unique Ids, this graph needed adjustment otherwise you'd have:
- dozens of Kafka graphs and only 
- 1 graph for all monte-carlo jobs and
- 1 graph for image-recognition jobs
Changes this
to this

Fix Spark summary graph jobsByName

---

universe/config.json

Specifying the default docker image twice means that the default installation doesn't work on local universes.
This change removes the default from `config.json` which makes the value specified in `resource.json` the default. This does not change behaviour, but makes it easier to use Spark from a local universe.
The alternative would be extensive documentation changes.

[COPS-3443] Make default docker image the one in resource.json

---

cli/dcos-spark/main.go
cli/dcos-spark/submit_builder.go
cli/dcos-spark/submit_builder_test.go
cli/dcos-spark/vendor/github.com/mattn/go-shellwords/.travis.yml
cli/dcos-spark/vendor/github.com/mattn/go-shellwords/LICENSE
cli/dcos-spark/vendor/github.com/mattn/go-shellwords/README.md
cli/dcos-spark/vendor/github.com/mattn/go-shellwords/_example/pipe.go
cli/dcos-spark/vendor/github.com/mattn/go-shellwords/shellwords.go
cli/dcos-spark/vendor/github.com/mattn/go-shellwords/shellwords_test.go
cli/dcos-spark/vendor/github.com/mattn/go-shellwords/util_go15.go
cli/dcos-spark/vendor/github.com/mattn/go-shellwords/util_posix.go
cli/dcos-spark/vendor/github.com/mattn/go-shellwords/util_windows.go
manifest.json
tests/jobs/scala/src/main/scala/MultiConfs.scala
tests/test_spark.py

Backport of #388 && #405 
This commit makes it possible to pass multi-argument configuration strings in the spark-cli.

[DCOS-38138] Update Spark CLI for shell-escape fix (#388)

---

tests/test_spark.py
universe/marathon.json.mustache

Backport of PR #411 && #414 
Replaces hardcoded VIP endpoint with `{{service.name}}`

[COPS-3550] Replace hardcoded VIP with service.name (#411)

---

manifest.json

Resolves [DCOS-47403](https://jira.mesosphere.com/browse/DCOS-47403)
Update Spark distribution version to the current release
* integration tests from current repo
* soak testing on DC/OS 1.10, 1.11, 1.11s, 1.12s, 1.13s
N/A

[DCOS-47403] Spark 2.3.2 release version bump

---

Dockerfile

Resolves [DCOS-49117](https://jira.mesosphere.com/browse/DCOS-49117)
- Switched base image from version to latest SHA tag,
- Installing R from Ubuntu package repository and removed build R from sources,
- Apache license added
- cleanup unused/irrelevant entries
Integration tests from this repo

[DCOS-49117] spark-build-image-refactoring

---

cli/dcos-spark/submit_builder.go
cli/dcos-spark/submit_builder_test.go
tests/jobs/scala/README.md
tests/jobs/scala/build.sbt
tests/jobs/scala/src/main/scala/ProvidedPackages.scala
tests/test_spark.py

Resolves [DCOS-33733](https://jira.mesosphere.com/browse/DCOS-33733)
* Spark CLI will support `--packages` flag in `submit-args` flag of `run` sub-command.
* While processing the `--packages` flag, It automatically sets `spark.jars.ivy` property to `/mnt/mesos/sandbox/.ivy2` as default location to download the jars.
* Unit Tests to verify setting of these properties: `spark.jars.packages=<maven_coordinates>` and `spark.jars.ivy=<ivy_user_dir>`.
* Integration test to verify that the mentioned packages in the flag is being downloaded in driver and executor.
* Added a custom class `ProvidedPackages`, to support the integration test.
* Unit Tests covering all the scenario of giving value to the flag and setting `spark.jars.ivy` property in the process.
* Running integration test …

[DCOS-33733] Enable support of --packages flag in Spark CLI

---

scale-tests/streaming_test.py
tests/integration/test_kafka.py
tests/jobs/scala/src/main/scala/KafkaJobs.scala

Resolves [DCOS-52116 Spark soak jobs fail due to dependency on norvig.com](https://jira.mesosphere.com/browse/DCOS-52116)
The external sample data file has been moved to a public S3 bucket with a test configuration change to use new location instead of norvig.com.
* Integration tests from this repository
* running affected soak jobs using the PR branch on 1.11s, 1.12s, and 1.13s clusters
N/A

[DCOS-52116] fix for failing Spark apps dependent on external test data

---

cli/dcos-spark/main.go
cli/dcos-spark/main_test.go
cli/dcos-spark/testdata/responses/unauthorized.html
cli/dcos-spark/vendor/github.com/mesosphere/dcos-commons/cli/README.md
cli/dcos-spark/vendor/github.com/mesosphere/dcos-commons/cli/client/response.go
cli/dcos-spark/vendor/vendor.json

Resolves [DCOS-33745] - Unhelpful error message in CLI when not logged in (https://jira.mesosphere.com/browse/DCOS-33745)
- Updated vendored dependency on dcos-commons which includes a fix for segfault on empty responses (https://jira.mesosphere.com/browse/DCOS-42966 - Kubernetes CLI can segfault)
- Added a custom check for "401 Unauthorized" response, to print a more helpful error message 
`<HTTP Method> request to <URL> was not authorized. Make sure you are logged in.`
instead of 
`dcos-beta-spark: error: invalid character '<' looking for beginning of value, try --help`
- Manually tested
- Added a unit test for CLI change
- [Bugfix] Improved error message in CLI when not logged into a cluster

[DCOS-33745] fetched cli segfault fix from dcos-commons, added a check for 401 response code

---

tests/test_spark.py

[DCOS-41592] - Adds an integration test for Mesos labels support in Spark
Resolves [DCOS-41592] - [Integration Tests] Add Mesos labels support to the Spark Dispatcher (https://jira.mesosphere.com/browse/DCOS-41592)
Adds an integration test that 
- Submits a job with parameter `--conf spark.mesos.driver.labels=foo:bar`
- Examines `dcos task --json <driver task id>` output and asserts that the label is present
The new integration test was run locally targeting a dc/os cluster in AWS.
n/a

[DCOS-41592] - Adds an integration test for Mesos labels support

---

tests/resources/dispatcher_submit_request_missing_args.json
tests/resources/dispatcher_submit_request_valid.json
tests/test_spark.py

Resolves [DCOS-41576](https://jira.mesosphere.com/browse/DCOS-41576)
Adds an integration test that sends a series of valid, invalid and valid again submission requests to spark dispatcher to verify it handles them as expected without going inactive (see SPARK-22574).
The new integration test was run locally targeting a dc/os cluster in AWS.
n/a

[DCOS-41576] - Adds an integration test for spark dispatcher inactivity fix (SPARK-22574)

---

tests/test_foldered_spark.py
tests/test_spark.py

Resolves [DCOS-53406: Fix race conditions in spark-build tests which uninstall DCOS spark CLI](https://jira.mesosphere.com/browse/DCOS-53406)
Tests for foldered Spark reinstall it with different names and then tear down. This led to environment modifications uninstalling Spark DCOS CLI and making the following tests fail. Also, uninstall procedures sometimes left stale ZK state which prevented subsequent jobs from execution. 
This change moves problematic tests to a separate module and provides fixtures and uninstall procedures which play along with the rest of the tests and don't cause conflicts.
* integration tests from this repository
N/A

[DCOS-41589] Extracted foldered Spark tests into a separate module

---

.gitignore
Makefile
conf/metrics.properties.template
docker/Dockerfile
spark-statsd-reporter/.gitignore
spark-statsd-reporter/README.md
spark-statsd-reporter/pom.xml
spark-statsd-reporter/src/main/java/org/apache/spark/metrics/sink/statsd/Configuration.java
spark-statsd-reporter/src/main/java/org/apache/spark/metrics/sink/statsd/InstanceDetails.java
spark-statsd-reporter/src/main/java/org/apache/spark/metrics/sink/statsd/InstanceDetailsProvider.java
spark-statsd-reporter/src/main/java/org/apache/spark/metrics/sink/statsd/InstanceType.java
spark-statsd-reporter/src/main/java/org/apache/spark/metrics/sink/statsd/MetricFormatter.java
spark-statsd-reporter/src/main/java/org/apache/spark/metrics/sink/statsd/MetricType.java
spark-statsd-reporter/src/main/java/org/apache/spark/metrics/sink/statsd/StatsdReporter.java
spark-statsd-reporter/src/main/java/org/apache/spark/metrics/sink/statsd/StatsdReporterException.java
spark-statsd-reporter/src/main/java/org/apache/spark/metrics/sink/statsd/StatsdSink.java

Resolves [DCOS-53535](https://jira.mesosphere.com/browse/DCOS-53535)
Dedicated StatsD metric reporter with tagging and metric name standardization support.
Original problem:
Spark assigns metric **names** using `spark.app.id` and `spark.executor.id` as a part of them. Thus the number of metrics is continuously growing because those IDs are unique between executions whereas the metrics themselves report the same thing. Another issue which arises here is how to use constantly changing metric names in dashboards.
For example, `jvm_heap_used` reported by all Spark instances (components):
- `jvm_heap_used` (Dispatcher)
- `<spark.app.id>_driver_jvm_heap_used` (driver)
- `<spark.app.id>_<spark.executor.id>_jvm_heap_used` (executor)
This PR provides PoC implementation of StatsD reporter which …

[DCOS-53535] Spark StatsD Metrics Reporter

---

conf/metrics.properties.template
spark-statsd-reporter/pom.xml
spark-statsd-reporter/src/main/java/org/apache/spark/metrics/sink/statsd/InstanceDetails.java
spark-statsd-reporter/src/main/java/org/apache/spark/metrics/sink/statsd/InstanceDetailsProvider.java
spark-statsd-reporter/src/main/java/org/apache/spark/metrics/sink/statsd/InstanceType.java
spark-statsd-reporter/src/main/java/org/apache/spark/metrics/sink/statsd/MetricFormatter.java
spark-statsd-reporter/src/main/java/org/apache/spark/metrics/sink/statsd/StatsdSink.java
spark-statsd-reporter/src/test/java/org/apache/spark/metrics/sink/statsd/InstanceDetailsProviderTest.java
spark-statsd-reporter/src/test/java/org/apache/spark/metrics/sink/statsd/MetricFormatterTest.java
spark-statsd-reporter/src/test/java/org/apache/spark/metrics/sink/statsd/StatsdReporterTest.java
spark-statsd-reporter/src/test/java/org/apache/spark/metrics/sink/statsd/StatsdSinkTest.java

Resolves [DCOS-54556](https://jira.mesosphere.com/browse/DCOS-54556)
- Removes _app_type_ and _instance_type_ tags from metrics.
- Adds mandatory _spark_ prefix to metrics, that can't be overridden
- Adds _spark_origin_ tag with value of SPARK_APP_ORIGIN environment variable
Manually and with unit tests
n/a

[DCOS-54556] Static config update for statsd reporter

---

history/universe/config.json
universe/config.json

This PR adds UI validation for service names for Spark and Spark History packages.
Resolves [DCOS-54117](https://jira.mesosphere.com/browse/DCOS-54117)
Regexp pattern added for service name validation.
Tested on a cluster with custom stubs for each package.
Results:

[DCOS-54117] Add service name validation for Spark and Spark-History

---

docs/install.md
universe/config.json

Resolves [DCOS-54708](https://jira.mesosphere.com/browse/DCOS-54708)
* Changed default value for `UCR_containerizer` parameter to `true`
* By running existing integration tests
* Enabled UCR containerizer by default for Spark Dispatcher

DCOS-54708: UCR containerizer by default

---

Makefile
bin/jenkins-dist-publish.sh
bin/jenkins-package-publish.sh
manifest.json
tests/jobs/python/shuffle_app.py
tests/test_spark_distributions.py

Resolves [DCOS-54709](https://jira.mesosphere.com/browse/DCOS-54709) - Add Scala 2.12 support for Spark
- Updated Makefile, and bin/jenkins-*.sh scripts to support multiple scala versions
- Updated manifest.json with new spark distributions with scala 2.12
- Default spark variant set to use hadoop-2.9 and scala 2.12
- Added a smoke test for custom spark docker images
I wanted to avoid creating test tags in git, so I tested the changes manually without using any production credentials, except uploading new spark distributions to downloads.mesosphere.io domain.
1)  Run the following script to build spark distribution archives:
```
SPARK_VERSION=2.4.3 \
DIST_DESTINATION_DIR=/tmp \
bin/jenkins-dist-publish.sh
```
Executed in `spark-tools` container, as described in the wiki. I had …

[DCOS-54709] Scala 2.12 support

---

manifest.json
tests/test_spark_distributions.py

Resolves [DCOS-58262](https://jira.mesosphere.com/browse/DCOS-58262)
- List docker images for different spark distributions in manifest.json
- The smoke test for custom docker images will now run automatically and use the images from manifest.json. The property for docker image is optional, but if any of the listed images does not exist, the test will be skipped.
- The smoke test for custom docker images will use GroupBy example job instead of shuffle_app.py
The test run in a standalone cluster in AWS. 
Note: I listed docker images from my personal repository for now, to make CI build more meaningful. I'll remove them before merging.

[DCOS-58262] - Docker images in the manifest

---

docker/Dockerfile

Resolves [DCOS-58773: Spark frameworks with CNI enabled failed to authenticate with the Mesos master](https://jira.mesosphere.com/browse/DCOS-58773)
This PR updates `libmesos` bundle version which comes with proper handling of TLS for DCOS 1.14 
and virtual networks.
- integration tests from this repo
- DCOS 1.14 tests run independently from the PR branch:
- [permissive](https://teamcity.mesosphere.io/viewLog.html?buildId=2279011&tab=buildResultsDiv&buildTypeId=DataServices_Spark_Nightly_DCOS_master_SparkBuild_master_permissive)
- [strict](https://teamcity.mesosphere.io/viewLog.html?buildId=2279012&tab=buildResultsDiv&buildTypeId=DataServices_Spark_Nightly_DCOS_master_SparkBuild_master_strict)
[Update] Updated `libmesos` to 1.14
[Update] Updated SDK (dcos-commons) to 0.57.0

[DCOS-58773] Updated libmesos to 1.14

---

tests/test_soak.py

Fixes failing job (https://soak114s.testing.mesosphe.re/#/jobs/detail/spark-hdfs-kerberos-terasort) on soak114 cluster. 
Before the main job execution, the clean-up job `hdfs-kerberos-delete-terasort-files` gets created, but it fails to execute with `no cluster attached` error. After some investigation, it was decided to replace  the old python script, used in soak110, with `dcos cli` command. 
Tested on majority of soak clusters with overriding `$GIT_BRANCH` job parameter. 
n/a

Modify cluster setup method to fix failing 'hdfs-kerberos-delete-terasort-files' job on soak114

---

docker/Dockerfile

With DCOS 1.14 Beta release we need to update `libmesos-bundle`. This PR updates `libmesos-bundle` from `1.14-alpha` to `1.14-beta`
- integration tests from this repo
* [Update] updated `libmesos-bundle` to `1.14-beta`

Updated libmesos-bundle from 1.14-alpha to 1.14-beta

---

monitoring/dashboards/SparkApplications.json
monitoring/dashboards/SparkClusterSummary.json

This PR adds json definitions of the dashboards to the repo so we have them as code instead of Jira ticket attachments. Relates to [DCOS-54704: Review and refactor Spark dashboards](https://jira.mesosphere.com/browse/DCOS-54704)
- testing is detailed in [this Jira ticket comment](https://jira.mesosphere.com/browse/DCOS-54704?focusedCommentId=272580&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-272580)
N/A

Added current version of Spark dashboards to the repo
